# Generated by Django 2.2.20 on 2021-04-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('symbol', models.CharField(blank=True, max_length=512, null=True, verbose_name='Symbol')),
                ('num_contract', models.IntegerField(default=3, verbose_name='Num. Contract')),
                ('tick', models.FloatField(blank=True, null=True, verbose_name='Tick Size')),
                ('long_dpp', models.FloatField(blank=True, null=True, verbose_name='DPP For Long')),
                ('long_dpp_up', models.IntegerField(default=4, verbose_name='Long DPP Up')),
                ('long_dpp_dn', models.IntegerField(default=4, verbose_name='Long DPP Down')),
                ('short_dpp', models.FloatField(blank=True, null=True, verbose_name='DPP For Short')),
                ('short_dpp_up', models.IntegerField(default=4, verbose_name='Short DPP Up')),
                ('short_dpp_dn', models.IntegerField(default=4, verbose_name='Short DPP Down')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated At')),
            ],
        ),
    ]
